/**
 * PR agent — creates and merges pull requests.
 *
 * Responsibilities:
 * - Creates a PR with a structured summary of the intent cycle
 * - Attaches quality gate result, success criteria, artifact list
 * - Auto-merges when all conditions are met
 *
 * Must never:
 * - Merge with an open GOLDEN_PRINCIPLE_BREACH signal
 * - Merge without a passing pipeline run
 * - Create a PR if the gate verdict is not 'pass'
 */

import type { DeployTask, DeployAgentResult, PullRequest, PRSummary } from '../types';

/**
 * Runs the PR agent for the given deploy task.
 * Creates a PR and returns it for the pipeline-agent to use.
 */
export async function runPRAgent(
  task: DeployTask,
  gitClient: GitClient,
): Promise<{ result: DeployAgentResult; pr: PullRequest | null }> {
  const startedAt = Date.now();

  // Hard stop — never create a PR if gate did not pass
  if (task.gateResult.verdict !== 'pass') {
    return {
      result: {
        agentRole: 'pr-agent',
        status: 'failed',
        signals: [{
          id: crypto.randomUUID(),
          correlationId: task.correlationId,
          type: 'CONSTRAINT_VIOLATION',
          severity: 'high',
          sourceAgent: 'pr-agent',
          message: `PR creation blocked: gate verdict is '${task.gateResult.verdict}', not 'pass'`,
          autoResolvable: false,
        }],
        durationMs: Date.now() - startedAt,
      },
      pr: null,
    };
  }

  try {
    const summary = buildPRSummary(task);
    const pr = await gitClient.createPR({
      title: buildPRTitle(task),
      body: renderPRBody(summary),
      branch: task.branch,
      targetBranch: 'main',
    });

    return {
      result: {
        agentRole: 'pr-agent',
        status: 'completed',
        signals: [],
        durationMs: Date.now() - startedAt,
      },
      pr,
    };
  } catch (err) {
    return {
      result: {
        agentRole: 'pr-agent',
        status: 'failed',
        signals: [{
          id: crypto.randomUUID(),
          correlationId: task.correlationId,
          type: 'CONTEXT_GAP',
          severity: 'high',
          sourceAgent: 'pr-agent',
          message: `PR creation failed: ${err instanceof Error ? err.message : String(err)}`,
          autoResolvable: false,
        }],
        durationMs: Date.now() - startedAt,
      },
      pr: null,
    };
  }
}

/**
 * Merges an approved PR. Hard-checks for GOLDEN_PRINCIPLE_BREACH before proceeding.
 * Called by pipeline-agent after a successful pipeline run.
 */
export async function mergePR(
  pr: PullRequest,
  task: DeployTask,
  gitClient: GitClient,
): Promise<DeployAgentResult> {
  const startedAt = Date.now();

  // GP-003: never merge with a GOLDEN_PRINCIPLE_BREACH
  const hasBreach = task.gateResult.signals?.some(
    (s) => s.type === 'GOLDEN_PRINCIPLE_BREACH',
  );
  if (hasBreach) {
    return {
      agentRole: 'pr-agent',
      status: 'failed',
      signals: [{
        id: crypto.randomUUID(),
        correlationId: task.correlationId,
        type: 'GOLDEN_PRINCIPLE_BREACH',
        severity: 'critical',
        sourceAgent: 'pr-agent',
        message: 'Merge blocked: GOLDEN_PRINCIPLE_BREACH signal present. Human approval required.',
        autoResolvable: false,
      }],
      durationMs: Date.now() - startedAt,
    };
  }

  await gitClient.mergePR(pr.externalPrId);

  return {
    agentRole: 'pr-agent',
    status: 'completed',
    signals: [],
    durationMs: Date.now() - startedAt,
  };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function buildPRTitle(task: DeployTask): string {
  const intentPreview = task.gateResult.correlationId.slice(0, 8);
  return `feat: agent-generated changes [${intentPreview}]`;
}

function buildPRSummary(task: DeployTask): PRSummary {
  return {
    intentText: '',  // populated from intent spec in Phase 2
    successCriteria: [],
    artifactPaths: task.artifactPaths,
    gateResult: {
      verdict: task.gateResult.verdict,
      signalCount: task.gateResult.signals.length,
      durationMs: task.gateResult.durationMs,
    },
    agentExecutionLog: [],
  };
}

function renderPRBody(summary: PRSummary): string {
  return [
    '## Gestalt — Generated PR',
    '',
    `**Intent:** ${summary.intentText || '_see intent spec_'}`,
    '',
    '### Success criteria',
    summary.successCriteria.length
      ? summary.successCriteria.map((c) => `- ${c}`).join('\n')
      : '_See intent spec_',
    '',
    '### Quality gate',
    `- Verdict: **${summary.gateResult.verdict}**`,
    `- Signals: ${summary.gateResult.signalCount}`,
    `- Duration: ${summary.gateResult.durationMs}ms`,
    '',
    '### Changed files',
    summary.artifactPaths.map((p) => `- \`${p}\``).join('\n'),
    '',
    '_Generated by Gestalt_',
  ].join('\n');
}

// ─── Git client interface (implemented per VCS in Phase 2) ───────────────────

export interface GitClient {
  createPR(params: {
    title: string;
    body: string;
    branch: string;
    targetBranch: string;
  }): Promise<PullRequest>;
  mergePR(externalPrId: string): Promise<void>;
}
